# Generated by Django 2.2.12 on 2023-05-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
