# Generated by Django 2.2.12 on 2023-05-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_formation_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Formation'),
        ),
    ]
