# Generated by Django 2.2.12 on 2023-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20230525_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
