# Generated by Django 2.2.12 on 2023-05-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20230529_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
