# Generated by Django 2.2.12 on 2023-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_responsable_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
