# Generated by Django 2.2.12 on 2023-05-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_employee_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bio',
            new_name='description',
        ),
    ]
