# Generated by Django 2.2.12 on 2023-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20230531_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pictures/'),
        ),
    ]
