# Generated by Django 2.2.12 on 2023-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20230627_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='duration',
        ),
        migrations.AddField(
            model_name='absence',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
