# Generated by Django 2.2.12 on 2023-06-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20230628_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='project.Employee'),
        ),
    ]
