# Generated by Django 2.2.12 on 2023-06-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_absence_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='employee',
        ),
    ]
