# Generated by Django 2.2.12 on 2023-06-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20230630_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='emp',
        ),
        migrations.AddField(
            model_name='absence',
            name='emp',
            field=models.ManyToManyField(related_name='absences', to='project.Employee'),
        ),
    ]
