# Generated by Django 2.2.12 on 2023-07-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20230630_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
